# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
